name: Feature Request
description: Request a new feature for this project
title: "[FEATURE]: "
labels:
  - "feature"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit this feature request!

        Please answer the following questions before submitting an issue.

        - [x] I am running the latest version
        - [x] I checked the documentation and found no answer
        - [x] I checked to make sure that this issue has not already been filed

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature.
      placeholder: "Example: As a [user role], I want to [complete action] so that I can [achieve outcome]"
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
